[package]
name = "lemonade_bootloader"
version = "0.1.0"
edition = "2018"

[build-dependencies]
bootloader = "0.11.10"
lemonade = { path = "lemonade", artifact = "bin" }

[dependencies]
ovmf-prebuilt = "0.2.1"

[workspace]
members = ["lemonade"]
