[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
bindeps = true

[build]
target = "x86_64-unknown-none"

[target.'cfg(target_os = "none")']
runner = "grub-bootimage runner"